blank_issues_enabled: false
contact_links:
  - name: 📖 Teacher's Guide
    url: https://github.com/ktanino10/skills-expand-your-team-with-copilot/blob/main/docs/teacher-guide.md
    about: Complete guide to using issue templates for activity management requests
  - name: General Questions
    url: https://github.com/ktanino10/skills-expand-your-team-with-copilot/discussions
    about: Ask questions about the activities system or get help with general usage
  - name: Documentation
    url: https://github.com/ktanino10/skills-expand-your-team-with-copilot/blob/main/src/README.md
    about: View the project documentation and development guide